const MODEL="openai/gpt-5.6-luna";
const IMAGE_MODEL="gpt-image-2";
const $=s=>document.querySelector(s);
const chat=$("#chat"),input=$("#input"),send=$("#send"),status=$("#status"),fileInput=$("#fileInput"),filePreview=$("#filePreview"),attach=$("#attach"),mic=$("#mic"),webMode=$("#webMode"),imageMode=$("#imageMode"),voiceMode=$("#voiceMode"),voicePanel=$("#voicePanel"),voiceStatus=$("#voiceStatus"),stopVoice=$("#stopVoice"),newChat=$("#newChat");
let messages=[],attachedFile=null,busy=false,recognition=null,voiceActive=false;
const userName=localStorage.getItem("astra6_user_name")||"";
function safeError(e){if(e==null)return "Неизвестная ошибка";if(typeof e==="string")return e;const x=e.message||e.msg||e.error||e.statusText;if(typeof x==="string")return x;try{return JSON.stringify(e)}catch{return String(e)}}
function setStatus(t){status.textContent=t}
function scroll(){chat.scrollTop=chat.scrollHeight}
function add(role,text=""){$("#welcome")?.remove();const row=document.createElement("div");row.className="message "+role;const av=document.createElement("div");av.className="avatar";av.textContent=role==="user"?"Вы":"✦";const body=document.createElement("div");body.className="message-body";const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=text;body.append(bubble);row.append(av,body);chat.append(row);scroll();return bubble}
function opts(){const o={model:MODEL,stream:true,normalize:true};if(webMode.checked)o.tools=[{type:"web_search"}];return o}
function ready(){return window.puter&&puter.ai&&typeof puter.ai.chat==="function"}
async function ensureReady(){if(ready())return;setStatus("Загрузка Джарвиса…");for(let i=0;i<30&&!ready();i++)await new Promise(r=>setTimeout(r,300));if(!ready())throw new Error("Сервис Джарвиса не загрузился. Проверьте интернет и обновите страницу.")}
function extractText(v){if(typeof v==="string")return v;if(!v)return "";if(typeof v.text==="string")return v.text;if(typeof v.content==="string")return v.content;if(v.message)return extractText(v.message);if(Array.isArray(v.content))return v.content.map(extractText).join("");return ""}
async function ask(text){text=text.trim();if(!text||busy)return;input.value="";input.style.height="auto";const file=attachedFile;clearFile();add("user",text+(file?`\n📎 ${file.name}`:""));const bubble=add("assistant","Джарвис думает…");busy=true;send.disabled=true;setStatus("Думает…");try{await ensureReady();const history=[{role:"system",content:`Ты — Джарвис, ИИ-помощник приложения Astra 6. Отвечай на русском по умолчанию. Будь точным, дружелюбным и полезным. Пользователя зовут ${userName||"друг"}; обращайся естественно, не в каждом сообщении.`},...messages,{role:"user",content:text}];const response=file?await puter.ai.chat(text,file,false,opts()):await puter.ai.chat(history,false,opts());let answer="";if(response&&typeof response[Symbol.asyncIterator]==="function"){for await(const part of response){if(part?.type==="error")throw new Error(safeError(part));const t=extractText(part);if(t){answer+=t;bubble.textContent=answer;scroll()}}}else{answer=extractText(response);bubble.textContent=answer||"Джарвис не вернул текстовый ответ."}if(!answer)throw new Error("AI вернул пустой ответ");messages.push({role:"user",content:text},{role:"assistant",content:answer});setStatus("Готово");if(voiceActive)speak(answer)}catch(e){console.error("Astra6",e);bubble.textContent="Не удалось получить ответ.\n\n"+safeError(e);setStatus("Ошибка — попробуйте ещё раз")}finally{busy=false;send.disabled=false;input.focus()}}
async function generateImage(prompt){prompt=prompt.trim();if(!prompt)return;add("user","Создай изображение: "+prompt);const bubble=add("assistant","Создаю…");busy=true;send.disabled=true;try{await ensureReady();const img=await puter.ai.txt2img(prompt,{model:IMAGE_MODEL,quality:"low"});bubble.textContent="Готово";img.className="result-image";bubble.parentElement.append(img);setStatus("Готово")}catch(e){bubble.textContent="Не удалось создать изображение.\n\n"+safeError(e);setStatus("Ошибка")}finally{busy=false;send.disabled=false}}
function clearFile(){attachedFile=null;filePreview.textContent="";filePreview.classList.remove("show");fileInput.value=""}
attach.onclick=()=>fileInput.click();fileInput.onchange=()=>{const f=fileInput.files?.[0];if(f){attachedFile=f;filePreview.textContent=`📎 ${f.name}  ×`;filePreview.classList.add("show")}};filePreview.onclick=clearFile;
send.onclick=()=>imageMode.checked?generateImage(input.value):ask(input.value);input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send.click()}};input.oninput=()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"};
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus("Голосовой ввод не поддерживается");return}if(recognition){try{recognition.stop()}catch{}}recognition=new SR();recognition.lang="ru-RU";recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{voiceActive=true;mic.textContent="■";voicePanel.hidden=false;voiceStatus.textContent="Говорите…";setStatus("Слушаю…")};recognition.onresult=e=>{input.value=Array.from(e.results).map(r=>r[0].transcript).join("");input.dispatchEvent(new Event("input"))};recognition.onerror=e=>{voiceStatus.textContent="Не удалось услышать речь";setStatus("Голос: "+safeError(e))};recognition.onend=()=>{voiceActive=false;mic.textContent="⌁";if(!busy&&input.value.trim())ask(input.value);else if(!busy)voiceStatus.textContent="Нажмите микрофон ещё раз";setStatus("Готово")};try{recognition.start()}catch(e){setStatus(safeError(e))}}
mic.onclick=()=>voiceActive?recognition?.stop():startRecognition();
function speak(text){if(!window.speechSynthesis||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ru-RU";u.rate=.98;u.pitch=1;window.speechSynthesis.speak(u)}
voiceMode.onclick=()=>{voicePanel.hidden=false;startRecognition()};stopVoice.onclick=()=>{try{recognition?.stop()}catch{}voicePanel.hidden=true;window.speechSynthesis?.cancel()};
newChat.onclick=()=>{messages=[];chat.innerHTML='<section class="welcome" id="welcome"><div class="welcome-mark">✦</div><h1>Чем могу помочь?</h1><p>Я Джарвис — помощник внутри Astra 6.</p></section>';input.focus()};
$("#menuBtn").onclick=()=>setStatus("Astra 6 • Джарвис");
setStatus("Готово");if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?v=6").catch(()=>{});
