const API_BASE=localStorage.getItem("astra6_api_base")||"";
const $=s=>document.querySelector(s);
const chat=$("#chat"),input=$("#input"),send=$("#send"),status=$("#status"),fileInput=$("#fileInput"),filePreview=$("#filePreview"),attach=$("#attach"),mic=$("#mic"),webMode=$("#webMode"),imageMode=$("#imageMode"),voiceMode=$("#voiceMode"),voicePanel=$("#voicePanel"),voiceStatus=$("#voiceStatus"),stopVoice=$("#stopVoice"),newChat=$("#newChat"),onboarding=$("#onboarding"),profileName=$("#profileName"),profileAge=$("#profileAge"),saveProfile=$("#saveProfile");
let messages=[],attachedFile=null,busy=false,recognition=null,voiceActive=false;
let userName=localStorage.getItem("astra6_user_name")||"";
const userAge=localStorage.getItem("astra6_user_age")||"";
function safeError(e){if(e==null)return "Неизвестная ошибка";if(typeof e==="string")return e;const x=e.message||e.msg||e.error||e.statusText;if(typeof x==="string")return x;try{return JSON.stringify(e)}catch{return String(e)}}
function errorText(e){const s=safeError(e);if(/401|403|unauthorized|api.?key/i.test(s))return "Сервер Astra 6 не подключён к ИИ. Нужно один раз настроить ключ на сервере.";if(/429|rate.?limit|quota/i.test(s))return "Лимит Astra 6 временно исчерпан. Попробуйте немного позже.";return s}
function setStatus(t){status.textContent=t}
function scroll(){chat.scrollTop=chat.scrollHeight}
function add(role,text=""){ $("#welcome")?.remove();const row=document.createElement("div");row.className="message "+role;const av=document.createElement("div");av.className="avatar";av.textContent=role==="user"?"Вы":"✦";const body=document.createElement("div");body.className="message-body";const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=text;body.append(bubble);row.append(av,body);chat.append(row);scroll();return bubble}
function endpoint(path){return `${API_BASE}${path}`}
async function api(path,options={}){const r=await fetch(endpoint(path),{...options,headers:{...(options.body instanceof FormData?{}:{"Content-Type":"application/json"}),...(options.headers||{})}});let data=null;try{data=await r.json()}catch{}if(!r.ok)throw new Error(data?.error||`Сервер вернул ошибку ${r.status}`);return data}
async function ask(text){text=text.trim();if(!text||busy)return;input.value="";input.style.height="auto";const file=attachedFile;clearFile();add("user",text+(file?`\n📎 ${file.name}`:""));const bubble=add("assistant","Джарвис думает…");busy=true;send.disabled=true;setStatus("Джарвис думает…");try{const history=[{role:"system",content:`Ты — Джарвис, ИИ-помощник приложения Astra 6. Отвечай на русском по умолчанию. Будь точным, дружелюбным, полезным и не выдумывай факты. Пользователя зовут ${userName||"друг"}; обращайся естественно, не в каждом сообщении.`},...messages,{role:"user",content:text}];let payload={messages:history,webSearch:webMode.checked};if(file){const reader=new FileReader();const fileData=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});payload.file={name:file.name,type:file.type,data:fileData}}const data=await api("/api/chat",{method:"POST",body:JSON.stringify(payload)});const answer=data?.text||data?.output||"";if(!answer)throw new Error("Сервер вернул пустой ответ");bubble.textContent=answer;messages.push({role:"user",content:text},{role:"assistant",content:answer});setStatus("Готово");if(voiceActive)speak(answer)}catch(e){console.error("Astra6",e);bubble.textContent="Не удалось получить ответ.\n\n"+errorText(e);setStatus("Ошибка — попробуйте ещё раз")}finally{busy=false;send.disabled=false;input.focus()}}
async function generateImage(prompt){prompt=prompt.trim();if(!prompt||busy)return;add("user","Создай изображение: "+prompt);const bubble=add("assistant","Создаю…");busy=true;send.disabled=true;setStatus("Создаю изображение…");try{const data=await api("/api/image",{method:"POST",body:JSON.stringify({prompt})});bubble.textContent="Готово";if(data?.url){const img=document.createElement("img");img.className="result-image";img.src=data.url;img.alt=prompt;bubble.parentElement.append(img)}else if(data?.b64){const img=document.createElement("img");img.className="result-image";img.src=`data:image/png;base64,${data.b64}`;img.alt=prompt;bubble.parentElement.append(img)}else throw new Error("Сервер не вернул изображение");setStatus("Готово")}catch(e){bubble.textContent="Не удалось создать изображение.\n\n"+errorText(e);setStatus("Ошибка")}finally{busy=false;send.disabled=false}}
function clearFile(){attachedFile=null;filePreview.textContent="";filePreview.classList.remove("show");fileInput.value=""}
attach.onclick=()=>fileInput.click();fileInput.onchange=()=>{const f=fileInput.files?.[0];if(f){attachedFile=f;filePreview.textContent=`📎 ${f.name}  ×`;filePreview.classList.add("show")}};filePreview.onclick=clearFile;
send.onclick=()=>imageMode.checked?generateImage(input.value):ask(input.value);input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send.click()}};input.oninput=()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"};
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus("Голосовой ввод не поддерживается");return}if(recognition){try{recognition.stop()}catch{}}recognition=new SR();recognition.lang="ru-RU";recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{voiceActive=true;mic.textContent="■";voicePanel.hidden=false;voiceStatus.textContent="Говорите…";setStatus("Слушаю…")};recognition.onresult=e=>{input.value=Array.from(e.results).map(r=>r[0].transcript).join("");input.dispatchEvent(new Event("input"))};recognition.onerror=e=>{voiceStatus.textContent="Не удалось услышать речь";setStatus("Голос: "+safeError(e))};recognition.onend=()=>{voiceActive=false;mic.textContent="⌁";if(!busy&&input.value.trim())ask(input.value);else if(!busy)voiceStatus.textContent="Нажмите микрофон ещё раз";setStatus("Готово")};try{recognition.start()}catch(e){setStatus(safeError(e))}}
mic.onclick=()=>voiceActive?recognition?.stop():startRecognition();
function speak(text){if(!window.speechSynthesis||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ru-RU";u.rate=.98;u.pitch=1;window.speechSynthesis.speak(u)}
voiceMode.onclick=()=>{voicePanel.hidden=false;startRecognition()};stopVoice.onclick=()=>{try{recognition?.stop()}catch{}voicePanel.hidden=true;window.speechSynthesis?.cancel()};
newChat.onclick=()=>{messages=[];chat.innerHTML='<section class="welcome" id="welcome"><div class="welcome-mark">✦</div><h1>Чем могу помочь?</h1><p>Я Джарвис — помощник внутри Astra 6.</p></section>';input.focus()};
$("#menuBtn").onclick=()=>setStatus(`Astra 6 • ${userName||"Джарвис"}`);
saveProfile.onclick=()=>{const n=profileName.value.trim(),a=profileAge.value.trim();if(!n){profileName.focus();return}if(!a||+a<1||+a>120){profileAge.focus();return}userName=n;localStorage.setItem("astra6_user_name",n);localStorage.setItem("astra6_user_age",a);onboarding.hidden=true;setStatus("Готово");input.focus()};
function init(){if(!userName||!userAge){onboarding.hidden=false;setTimeout(()=>profileName.focus(),100)}else input.focus();setStatus("Готово")}
init();
