const MODEL="openai/gpt-5.6-luna";
const IMAGE_MODEL="gpt-image-2";
const $=s=>document.querySelector(s);
const status=$("#status"),chat=$("#chat"),input=$("#input"),send=$("#send"),fileInput=$("#fileInput"),attach=$("#attach"),imageMode=$("#imageMode"),webMode=$("#webMode"),mic=$("#mic"),filePreview=$("#filePreview");
const nameCard=$("#nameCard"),nameSuggestion=$("#nameSuggestion"),acceptName=$("#acceptName"),changeName=$("#changeName"),customName=$("#customName"),nameInput=$("#nameInput"),saveName=$("#saveName");
let messages=[],attachedFile=null,userName=localStorage.getItem("astra6_user_name")||"",suggestedName="";
const suggestions=["Владимир","Шеф","Капитан","Командир","Друг"];
function scroll(){chat.scrollTop=chat.scrollHeight}
function setStatus(t){if(status)status.textContent=t}
function add(role,text=""){ $("#welcome")?.remove(); const row=document.createElement("div");row.className="message "+role;const av=document.createElement("div");av.className="avatar";av.textContent=role==="user"?"Вы":"✦";const body=document.createElement("div");body.className="message-body";const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=text;body.append(bubble);row.append(av,body);chat.append(row);scroll();return bubble }
function applyName(name){name=(name||"").trim().replace(/\s+/g," ").slice(0,32);if(!name)return false;userName=name;localStorage.setItem("astra6_user_name",name);nameCard.hidden=true;setStatus(`Astra 6 • Джарвис • ${name}`);return true}
function initName(){if(userName){nameCard.hidden=true;return}suggestedName=suggestions[Math.floor(Math.random()*suggestions.length)];nameSuggestion.textContent=`Я предлагаю обращаться к вам «${suggestedName}». Если хотите, можно выбрать своё имя.`;acceptName.textContent=`✨ Да, «${suggestedName}»`;acceptName.onclick=()=>applyName(suggestedName);changeName.onclick=()=>{customName.hidden=false;nameInput.hidden=false;saveName.hidden=false;nameInput.focus()};saveName.onclick=()=>{if(!applyName(nameInput.value)){nameInput.focus();nameInput.placeholder="Введите имя"}};nameInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();saveName.click()}})}
initName();
const SYSTEM=()=>`Ты — Джарвис, ИИ-помощник внутри приложения Astra 6. Название приложения всегда Astra 6, твоё имя всегда Джарвис. Отвечай на русском, если не попросили другой язык. Будь быстрым, точным и естественным. Помогай с учёбой, математикой, физикой, инженерией, кодом, играми, файлами, изображениями и актуальной информацией. Не выдумывай факты и источники. Пользователя называй «${userName||"друг"}» естественно, не в каждом предложении.`;
let authPromise=null;
async function ensureAuth(){if(!window.puter||!puter.ai)throw new Error("AI-сервис ещё загружается. Подождите несколько секунд и повторите.");if(puter.auth?.isSignedIn?.()||puter.authToken)return;if(authPromise)return authPromise;authPromise=(async()=>{setStatus("Запускаю гостевой режим…");try{if(puter.auth?.signIn){const r=await puter.auth.signIn({attempt_temp_user_creation:true});if(r?.success===false)throw new Error(r.msg||r.error||"гостевой режим недоступен")}else if(!puter.authToken){throw new Error("Гостевой режим этого браузера недоступен")}}finally{authPromise=null}})();return authPromise}
function opts(){const o={model:MODEL,stream:true};if(webMode.checked)o.tools=[{type:"web_search"}];return o}
async function ask(text){text=text.trim();if(!text)return;if(!userName)applyName(suggestedName||"Друг");input.value="";input.style.height="auto";const file=attachedFile;clearFile();add("user",text+(file?`\n📎 ${file.name}`:""));const bubble=add("assistant","Джарвис подключается…");send.disabled=true;setStatus(webMode.checked?"Джарвис ищет информацию…":"Джарвис думает…");try{await ensureAuth();const history=[{role:"system",content:SYSTEM()},...messages,{role:"user",content:text}];let response=file?await puter.ai.chat(text,file,false,opts()):await puter.ai.chat(history,false,opts());let answer="";if(response&&response[Symbol.asyncIterator]){for await(const part of response){if(part?.type==="error")throw new Error(part.message||"Ошибка AI");if(part?.type==="text"&&part.text){answer+=part.text;bubble.textContent=answer;scroll()}else if(part?.text){answer+=part.text;bubble.textContent=answer;scroll()}}}else{answer=response?.message?.content||response?.text||"";bubble.textContent=answer||"Пустой ответ от AI."}if(!answer)throw new Error("AI не вернул текстовый ответ");messages.push({role:"user",content:text},{role:"assistant",content:answer});setStatus(`Astra 6 • Джарвис • готова${userName?` • ${userName}`:""}`)}catch(e){console.error(e);bubble.textContent="Не удалось получить ответ.\n\n"+(e?.message||e)+"\n\nПроверьте интернет и нажмите «Отправить» ещё раз.";setStatus("Ошибка подключения")}finally{send.disabled=false;input.focus()}}
async function generateImage(prompt){prompt=prompt.trim();if(!prompt)return;if(!userName)applyName(suggestedName||"Друг");input.value="";input.style.height="auto";add("user","🎨 Создай изображение: "+prompt);const bubble=add("assistant","Джарвис создаёт изображение…");send.disabled=true;setStatus("Генерация изображения…");try{await ensureAuth();const img=await puter.ai.txt2img(prompt,{model:IMAGE_MODEL,quality:"low"});bubble.remove();const row=document.createElement("div");row.className="message assistant";const av=document.createElement("div");av.className="avatar";av.textContent="✦";const body=document.createElement("div");body.className="message-body";const title=document.createElement("div");title.className="bubble";title.textContent="Готово ✨";img.className="result-image";body.append(title,img);row.append(av,body);chat.append(row);scroll();setStatus("Astra 6 • Джарвис • готова")}catch(e){bubble.textContent="Не получилось создать изображение:\n"+(e?.message||e);setStatus("Ошибка генерации")}finally{send.disabled=false;input.focus()}}
function clearFile(){attachedFile=null;filePreview.textContent="";filePreview.classList.remove("show");fileInput.value=""}
attach.onclick=()=>fileInput.click();fileInput.addEventListener("change",()=>{const f=fileInput.files?.[0];if(f){attachedFile=f;filePreview.textContent=`📎 ${f.name} · ${(f.size/1024/1024).toFixed(1)} МБ  ×`;filePreview.classList.add("show")}});filePreview.onclick=clearFile;
send.onclick=()=>imageMode.checked?generateImage(input.value):ask(input.value);input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send.click()}});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,150)+"px"});document.querySelectorAll(".cards button").forEach(b=>b.onclick=()=>{input.value=b.dataset.prompt||b.textContent.replace(/^.\s/,"");input.focus();input.dispatchEvent(new Event("input"))});
if(mic&&(window.SpeechRecognition||window.webkitSpeechRecognition)){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,rec=new SR();rec.lang="ru-RU";rec.interimResults=true;mic.onclick=()=>{try{rec.start();mic.classList.add("active")}catch{}};rec.onresult=e=>{input.value=Array.from(e.results).map(r=>r[0].transcript).join("");input.dispatchEvent(new Event("input"))};rec.onend=()=>mic.classList.remove("active")}else if(mic){mic.disabled=true}
setStatus(`Astra 6 • Джарвис • готова${userName?` • ${userName}`:""}`);if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?4").catch(()=>{});